#include "PythonHelpers.h"

#include "Spellbook.h"
#include "Inventory.h"
#include "Interface.h"
#include "Scriptable/PCStatStruct.h"

#include "GUIScript.h"

#define UNINIT_IEDWORD 0xcccccccc

#ifndef PyDoc_STRVAR
#define PyDoc_STRVAR(name,str) PyDoc_VAR(name) = PyDoc_STR(str)
#endif

//this stuff is missing from Python 2.2
#ifndef PyDoc_VAR
#define PyDoc_VAR(name) static char name[]
#endif

#ifndef PyDoc_STR
# ifdef WITH_DOC_STRINGS
# define PyDoc_STR(str) str
# else
# define PyDoc_STR(str) ""
# endif
#endif

using namespace GemRB;

struct UsedItemType {
	ieResRef itemname;
	ieVariable username; //death variable
	ieStrRef value;
	int flags;
};

extern int SpecialItemsCount;
extern int StoreSpellsCount;
extern int UsedItemsCount;

extern SpellDescType *SpecialItems;

extern SpellDescType *StoreSpells;
extern ItemExtHeader *ItemArray;
extern SpellExtHeader *SpellArray;
extern UsedItemType *UsedItems;

extern int ReputationIncrease[20];
extern int ReputationDonation[20];

extern ieDword GUIAction[MAX_ACT_COUNT];

extern char gametype_hint[100];
extern int gametype_hint_weight;


extern char const * const GemRB_SetInfoTextColor__doc;
extern char const * const GemRB_UnhideGUI__doc;
extern char const * const GemRB_HideGUI__doc;
extern char const * const GemRB_GetGameString__doc;
extern char const * const GemRB_LoadGame__doc;
extern char const * const GemRB_EnterGame__doc;
extern char const * const GemRB_QuitGame__doc;
extern char const * const GemRB_TextArea_SetChapterText__doc;
extern char const * const GemRB_StatComment__doc;
extern char const * const GemRB_GetString__doc;
extern char const * const GemRB_EndCutSceneMode__doc;
extern char const * const GemRB_Window_ReassignControls__doc;
extern char const * const GemRB_LoadWindowPack__doc;
extern char const * const GemRB_LoadWindow__doc;
extern char const * const GemRB_Window_SetSize__doc;
extern char const * const GemRB_Window_SetFrame__doc;
extern char const * const GemRB_LoadWindowFrame__doc;
extern char const * const GemRB_EnableCheatKeys__doc;
extern char const * const GemRB_Window_SetPicture__doc;
extern char const * const GemRB_Window_SetPos__doc;
extern char const * const GemRB_Window_GetRect__doc;
extern char const * const GemRB_LoadTable__doc;
extern char const * const GemRB_Table_Unload__doc;
extern char const * const GemRB_Table_GetValue__doc;
extern char const * const GemRB_Table_FindValue__doc;
extern char const * const GemRB_Table_GetRowIndex__doc;
extern char const * const GemRB_Table_GetRowName__doc;
extern char const * const GemRB_Table_GetColumnIndex__doc;
extern char const * const GemRB_Table_GetColumnName__doc;
extern char const * const GemRB_Table_GetRowCount__doc;
extern char const * const GemRB_Table_GetColumnCount__doc;
extern char const * const GemRB_LoadSymbol__doc;
extern char const * const GemRB_Symbol_Unload__doc;
extern char const * const GemRB_Symbol_GetValue__doc;
extern char const * const GemRB_Window_GetControl__doc;
extern char const * const GemRB_Window_HasControl__doc;
extern char const * const GemRB_Control_QueryText__doc;
extern char const * const GemRB_TextEdit_SetBufferLength__doc;
extern char const * const GemRB_Control_SetText__doc;
extern char const * const GemRB_TextArea_Append__doc;
extern char const * const GemRB_TextArea_Clear__doc;
extern char const * const GemRB_Control_SetTooltip__doc;
extern char const * const GemRB_Window_SetVisible__doc;
extern char const * const GemRB_SetMasterScript__doc;
extern char const * const GemRB_Window_ShowModal__doc;
extern char const * const GemRB_SetTimedEvent__doc;
extern char const * const GemRB_Control_SetEvent__doc;
extern char const * const GemRB_Window_SetKeyPressEvent__doc;
extern char const * const GemRB_SetNextScript__doc;
extern char const * const GemRB_Control_SetStatus__doc;
extern char const * const GemRB_Control_AttachScrollBar__doc;
extern char const * const GemRB_Control_SetVarAssoc__doc;
extern char const * const GemRB_Window_Unload__doc;
extern char const * const GemRB_Window_Invalidate__doc;
extern char const * const GemRB_CreateWindow__doc;
extern char const * const GemRB_Button_CreateLabelOnButton__doc;
extern char const * const GemRB_Window_CreateLabel__doc;
extern char const * const GemRB_Label_SetTextColor__doc;
extern char const * const GemRB_Window_CreateTextEdit__doc;
extern char const * const GemRB_Window_CreateScrollBar__doc;
extern char const * const GemRB_Window_CreateButton__doc;
extern char const * const GemRB_TextEdit_SetBackground__doc;
extern char const * const GemRB_Button_SetSprites__doc;
extern char const * const GemRB_Button_SetOverlay__doc;
extern char const * const GemRB_Button_SetBorder__doc;
extern char const * const GemRB_Button_EnableBorder__doc;
extern char const * const GemRB_Button_SetFont__doc;
extern char const * const GemRB_Button_SetAnchor__doc;
extern char const * const GemRB_Button_SetPushOffset__doc;
extern char const * const GemRB_Button_SetTextColor__doc;
extern char const * const GemRB_Window_DeleteControl__doc;
extern char const * const GemRB_AddNewArea__doc;
extern char const * const GemRB_WorldMap_AdjustScrolling__doc;
extern char const * const GemRB_CreateMovement__doc;
extern char const * const GemRB_UpdateWorldMap__doc;
extern char const * const GemRB_WorldMap_GetDestinationArea__doc;
extern char const * const GemRB_Window_CreateWorldMapControl__doc;
extern char const * const GemRB_WorldMap_SetTextColor__doc;
extern char const * const GemRB_Window_CreateMapControl__doc;
extern char const * const GemRB_Control_SubstituteForControl__doc;
extern char const * const GemRB_Control_SetPos__doc;
extern char const * const GemRB_Control_GetRect__doc;
extern char const * const GemRB_Control_SetSize__doc;
extern char const * const GemRB_Label_SetFont__doc;
extern char const * const GemRB_Label_SetUseRGB__doc;
extern char const * const GemRB_GameSetPartySize__doc;
extern char const * const GemRB_GameSetProtagonistMode__doc;
extern char const * const GemRB_GameGetExpansion__doc;
extern char const * const GemRB_GameSetExpansion__doc;
extern char const * const GemRB_GameSetScreenFlags__doc;
extern char const * const GemRB_GameControlSetScreenFlags__doc;
extern char const * const GemRB_GameControlSetTargetMode__doc;
extern char const * const GemRB_GameControlGetTargetMode__doc;
extern char const * const GemRB_GameControlToggleAlwaysRun__doc;
extern char const * const GemRB_Button_SetFlags__doc;
extern char const * const GemRB_TextArea_SetFlags__doc;
extern char const * const GemRB_ScrollBar_SetDefaultScrollBar__doc;
extern char const * const GemRB_Button_SetState__doc;
extern char const * const GemRB_Button_SetPictureClipping__doc;
extern char const * const GemRB_Button_SetPicture__doc;
extern char const * const GemRB_Button_SetSprite2D__doc;
extern char const * const GemRB_Button_SetMOS__doc;
extern char const * const GemRB_Button_SetPLT__doc;
extern char const * const GemRB_Button_SetBAM__doc;
extern char const * const GemRB_Control_SetAnimationPalette__doc;
extern char const * const GemRB_Control_HasAnimation__doc;
extern char const * const GemRB_Control_SetAnimation__doc;
extern char const * const GemRB_ValidTarget__doc;
extern char const * const GemRB_VerbalConstant__doc;
extern char const * const GemRB_PlaySound__doc;
extern char const * const GemRB_DrawWindows__doc;
extern char const * const GemRB_Quit__doc;
extern char const * const GemRB_LoadMusicPL__doc;
extern char const * const GemRB_SoftEndPL__doc;
extern char const * const GemRB_HardEndPL__doc;
extern char const * const GemRB_SetToken__doc;
extern char const * const GemRB_SetVar__doc;
extern char const * const GemRB_GetMessageWindowSize__doc;
extern char const * const GemRB_GetToken__doc;
extern char const * const GemRB_GetVar__doc;
extern char const * const GemRB_CheckVar__doc;
extern char const * const GemRB_SetGlobal__doc;
extern char const * const GemRB_GetGameVar__doc;
extern char const * const GemRB_PlayMovie__doc;
extern char const * const GemRB_DumpActor__doc;
extern char const * const GemRB_SaveCharacter__doc;
extern char const * const GemRB_SaveConfig__doc;
extern char const * const GemRB_SaveGame__doc;
extern char const * const GemRB_GetSaveGames__doc;
extern char const * const GemRB_DeleteSaveGame__doc;
extern char const * const GemRB_SaveGame_GetName__doc;
extern char const * const GemRB_SaveGame_GetDate__doc;
extern char const * const GemRB_SaveGame_GetGameDate__doc;
extern char const * const GemRB_SaveGame_GetSaveID__doc;
extern char const * const GemRB_SaveGame_GetPreview__doc;
extern char const * const GemRB_SaveGame_GetPortrait__doc;
extern char const * const GemRB_GetGamePreview__doc;
extern char const * const GemRB_GetGamePortraitPreview__doc;
extern char const * const GemRB_Roll__doc;
extern char const * const GemRB_Window_CreateTextArea__doc;
extern char const * const GemRB_TextArea_ListResources__doc;
extern char const * const GemRB_TextArea_SetOptions__doc;
extern char const * const GemRB_GetPartySize__doc;
extern char const * const GemRB_GetGameTime__doc;
extern char const * const GemRB_GameGetReputation__doc;
extern char const * const GemRB_GameSetReputation__doc;
extern char const * const GemRB_IncreaseReputation__doc;
extern char const * const GemRB_GameGetPartyGold__doc;
extern char const * const GemRB_GameSetPartyGold__doc;
extern char const * const GemRB_GameGetFormation__doc;
extern char const * const GemRB_GameSetFormation__doc;
extern char const * const GemRB_GetJournalSize__doc;
extern char const * const GemRB_GetJournalEntry__doc;
extern char const * const GemRB_SetJournalEntry__doc;
extern char const * const GemRB_GameIsBeastKnown__doc;
extern char const * const GemRB_GetINIPartyCount__doc;
extern char const * const GemRB_GetINIQuestsKey__doc;
extern char const * const GemRB_GetINIBeastsKey__doc;
extern char const * const GemRB_GetINIPartyKey__doc;
extern char const * const GemRB_CreatePlayer__doc;
extern char const * const GemRB_GetPlayerStates__doc;
extern char const * const GemRB_GetPlayerName__doc;
extern char const * const GemRB_SetPlayerName__doc;
extern char const * const GemRB_CreateString__doc;
extern char const * const GemRB_SetPlayerString__doc;
extern char const * const GemRB_SetPlayerSound__doc;
extern char const * const GemRB_GetPlayerSound__doc;
extern char const * const GemRB_GetSlotType__doc;
extern char const * const GemRB_GetPCStats__doc;
extern char const * const GemRB_GameSelectPC__doc;
extern char const * const GemRB_GameIsPCSelected__doc;
extern char const * const GemRB_GameSelectPCSingle__doc;
extern char const * const GemRB_GameGetSelectedPCSingle__doc;
extern char const * const GemRB_GameGetFirstSelectedPC__doc;
extern char const * const GemRB_GameGetFirstSelectedActor__doc;
extern char const * const GemRB_GameControlSetLastActor__doc;
extern char const * const GemRB_ActOnPC__doc;
extern char const * const GemRB_GetPlayerPortrait__doc;
extern char const * const GemRB_GetPlayerString__doc;
extern char const * const GemRB_GetPlayerStat__doc;
extern char const * const GemRB_SetPlayerStat__doc;
extern char const * const GemRB_GetPlayerScript__doc;
extern char const * const GemRB_SetPlayerScript__doc;
extern char const * const GemRB_SetPlayerDialog__doc;
extern char const * const GemRB_FillPlayerInfo__doc;
extern char const * const GemRB_Button_SetSpellIcon__doc;
extern char const * const GemRB_Button_SetItemIcon__doc;
extern char const * const GemRB_EnterStore__doc;
extern char const * const GemRB_LeaveStore__doc;
extern char const * const GemRB_LoadRighthandStore__doc;
extern char const * const GemRB_CloseRighthandStore__doc;
extern char const * const GemRB_LeaveContainer__doc;
extern char const * const GemRB_GetContainer__doc;
extern char const * const GemRB_GetContainerItem__doc;
extern char const * const GemRB_ChangeContainerItem__doc;
extern char const * const GemRB_GetStore__doc;
extern char const * const GemRB_IsValidStoreItem__doc;
extern char const * const GemRB_FindStoreItem__doc;
extern char const * const GemRB_SetPurchasedAmount__doc;
extern char const * const GemRB_ChangeStoreItem__doc;
extern char const * const GemRB_GetStoreItem__doc;
extern char const * const GemRB_GetStoreDrink__doc;
extern char const * const GemRB_GetStoreCure__doc;
extern char const * const GemRB_ExecuteString__doc;
extern char const * const GemRB_EvaluateString__doc;
extern char const * const GemRB_UpdateMusicVolume__doc;
extern char const * const GemRB_UpdateAmbientsVolume__doc;
extern char const * const GemRB_MessageWindowDebug__doc;
extern char const * const GemRB_GetCurrentArea__doc;
extern char const * const GemRB_MoveToArea__doc;
extern char const * const GemRB_GetMemorizableSpellsCount__doc;
extern char const * const GemRB_SetMemorizableSpellsCount__doc;
extern char const * const GemRB_CountSpells__doc;
extern char const * const GemRB_GetKnownSpellsCount__doc;
extern char const * const GemRB_GetKnownSpell__doc;
extern char const * const GemRB_GetMemorizedSpellsCount__doc;
extern char const * const GemRB_GetMemorizedSpell__doc;
extern char const * const GemRB_GetSpell__doc;
extern char const * const GemRB_CheckSpecialSpell__doc;
extern char const * const GemRB_GetSpelldataIndex__doc;
extern char const * const GemRB_GetSpelldata__doc;
extern char const * const GemRB_LearnSpell__doc;
extern char const * const GemRB_DispelEffect__doc;
extern char const * const GemRB_RemoveEffects__doc;
extern char const * const GemRB_RemoveSpell__doc;
extern char const * const GemRB_RemoveItem__doc;
extern char const * const GemRB_MemorizeSpell__doc;
extern char const * const GemRB_UnmemorizeSpell__doc;
extern char const * const GemRB_GetSlotItem__doc;
extern char const * const GemRB_ChangeItemFlag__doc;
extern char const * const GemRB_CanUseItemType__doc;
extern char const * const GemRB_GetSlots__doc;
extern char const * const GemRB_FindItem__doc;
extern char const * const GemRB_GetItem__doc;
extern char const * const GemRB_DragItem__doc;
extern char const * const GemRB_DropDraggedItem__doc;
extern char const * const GemRB_IsDraggingItem__doc;
extern char const * const GemRB_GetSystemVariable__doc;
extern char const * const GemRB_CreateItem__doc;
extern char const * const GemRB_GetAvatarsValue__doc;
extern char const * const GemRB_SetMapAnimation__doc;
extern char const * const GemRB_SetMapnote__doc;
extern char const * const GemRB_SetMapDoor__doc;
extern char const * const GemRB_SetMapExit__doc;
extern char const * const GemRB_SetMapRegion__doc;
extern char const * const GemRB_CreateCreature__doc;
extern char const * const GemRB_RevealArea__doc;
extern char const * const GemRB_ExploreArea__doc;
extern char const * const GemRB_GetRumour__doc;
extern char const * const GemRB_GamePause__doc;
extern char const * const GemRB_CheckFeatCondition__doc;
extern char const * const GemRB_HasFeat__doc;
extern char const * const GemRB_SetFeat__doc;
extern char const * const GemRB_GetMaxEncumbrance__doc;
extern char const * const GemRB_GetAbilityBonus__doc;
extern char const * const GemRB_LeaveParty__doc;
extern char const * const GemRB_Button_SetActionIcon__doc;
extern char const * const GemRB_HasResource__doc;
extern char const * const GemRB_Window_SetupEquipmentIcons__doc;
extern char const * const GemRB_Window_SetupControls__doc;
extern char const * const GemRB_ClearActions__doc;
extern char const * const GemRB_SetDefaultActions__doc;
extern char const * const GemRB_SetupQuickSpell__doc;
extern char const * const GemRB_SetupQuickSlot__doc;
extern char const * const GemRB_SetEquippedQuickSlot__doc;
extern char const * const GemRB_GetEquippedQuickSlot__doc;
extern char const * const GemRB_GetEquippedAmmunition__doc;
extern char const * const GemRB_SetModalState__doc;
extern char const * const GemRB_PrepareSpontaneousCast__doc;
extern char const * const GemRB_SpellCast__doc;
extern char const * const GemRB_ApplySpell__doc;
extern char const * const GemRB_UseItem__doc;
extern char const * const GemRB_SetGamma__doc;
extern char const * const GemRB_SetMouseScrollSpeed__doc;
extern char const * const GemRB_SetTooltipDelay__doc;
extern char const * const GemRB_SetFullScreen__doc;
extern char const * const GemRB_RunRestScripts__doc;
extern char const * const GemRB_RestParty__doc;
extern char const * const GemRB_ChargeSpells__doc;
extern char const * const GemRB_HasSpecialItem__doc;
extern char const * const GemRB_HasSpecialSpell__doc;
extern char const * const GemRB_ApplyEffect__doc;
extern char const * const GemRB_CountEffects__doc;
extern char const * const GemRB_ModifyEffect__doc;
extern char const * const GemRB_StealFailed__doc;
extern char const * const GemRB_SwapPCs__doc;
extern char const * const GemRB_SetRepeatClickFlags__doc;
extern char const * const GemRB_DisplayString__doc;
extern char const * const GemRB_GetCombatDetails__doc;
extern char const * const GemRB_GetDamageReduction__doc;
extern char const * const GemRB_GetSpellFailure__doc;
extern char const * const GemRB_IsDualWielding__doc;
extern char const * const GemRB_GetSelectedSize__doc;
extern char const * const GemRB_GetSelectedActors__doc;
extern char const * const GemRB_GetSpellCastOn__doc;
extern char const * const GemRB_SetTickHook__doc;
extern char const * const GemRB_SetupMaze__doc;
extern char const * const GemRB_SetMazeEntry__doc;
extern char const * const GemRB_SetMazeData__doc;
extern char const * const GemRB_GetMazeHeader__doc;
extern char const * const GemRB_GetMazeEntry__doc;
extern char const * const GemRB_AddGameTypeHint__doc;
extern char const * const GemRB_GetAreaInfo__doc;
extern char const * const GemRB_Log__doc;
extern char const * const GemRB_SetFeature__doc;
extern char const * const GemRB_GetMultiClassPenalty__doc;

PyObject* GemRB_SetInfoTextColor(PyObject*, PyObject* args);
PyObject* GemRB_UnhideGUI(PyObject*, PyObject* /*args*/);
PyObject* GemRB_HideGUI(PyObject*, PyObject* /*args*/);
PyObject* GemRB_GetGameString(PyObject*, PyObject* args);
PyObject* GemRB_LoadGame(PyObject*, PyObject* args);
PyObject* GemRB_EnterGame(PyObject*, PyObject* /*args*/);
PyObject* GemRB_QuitGame(PyObject*, PyObject* /*args*/);
PyObject* GemRB_TextArea_SetChapterText(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_StatComment(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_EndCutSceneMode(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_Window_ReassignControls(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LoadWindowPack(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LoadWindow(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetSize(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetFrame(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LoadWindowFrame(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_EnableCheatKeys(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetPicture(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetPos(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_GetRect(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LoadTable(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_Unload(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetValue(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_FindValue(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetRowIndex(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetRowName(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetColumnIndex(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetColumnName(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetRowCount(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Table_GetColumnCount(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LoadSymbol(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Symbol_Unload(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Symbol_GetValue(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_GetControl(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_HasControl(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_QueryText(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextEdit_SetBufferLength(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetText(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextArea_Append(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextArea_Clear(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetTooltip(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetVisible(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMasterScript(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_ShowModal(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetTimedEvent(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetEvent(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetKeyPressEvent(PyObject* /*self*/, PyObject *args);
PyObject* GemRB_SetNextScript(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetStatus(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_AttachScrollBar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetVarAssoc(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_Unload(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_Invalidate(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CreateWindow(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_CreateLabelOnButton(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateLabel(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Label_SetTextColor(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateTextEdit(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateScrollBar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateButton(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextEdit_SetBackground(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetSprites(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetOverlay(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetBorder(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_EnableBorder(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetFont(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetAnchor(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetPushOffset(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetTextColor(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_DeleteControl(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_AddNewArea(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_WorldMap_AdjustScrolling(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CreateMovement(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_UpdateWorldMap(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_WorldMap_GetDestinationArea(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateWorldMapControl(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_WorldMap_SetTextColor(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateMapControl(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SubstituteForControl(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetPos(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_GetRect(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetSize(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Label_SetFont(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Label_SetUseRGB(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameSetPartySize(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameSetProtagonistMode(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameGetExpansion(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameSetExpansion(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameSetScreenFlags(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameControlSetScreenFlags(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameControlSetTargetMode(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameControlGetTargetMode(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameControlToggleAlwaysRun(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_Button_SetFlags(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextArea_SetFlags(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ScrollBar_SetDefaultScrollBar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetState(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetPictureClipping(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetPicture(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetSprite2D(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetMOS(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetPLT(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetBAM(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetAnimationPalette(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_HasAnimation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Control_SetAnimation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ValidTarget(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_VerbalConstant(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_PlaySound(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_DrawWindows(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_Quit(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_LoadMusicPL(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SoftEndPL(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_HardEndPL(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_SetToken(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetVar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetMessageWindowSize(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GetToken(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetVar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CheckVar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetGlobal(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetGameVar(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_PlayMovie(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_DumpActor(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_SaveCharacter(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_SaveConfig(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_SaveGame(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_GetSaveGames(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_DeleteSaveGame(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SaveGame_GetName(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SaveGame_GetDate(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SaveGame_GetGameDate(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SaveGame_GetSaveID(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SaveGame_GetPreview(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SaveGame_GetPortrait(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetGamePreview(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetGamePortraitPreview(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Roll(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_CreateTextArea(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextArea_ListResources(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_TextArea_SetOptions(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPartySize(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_GetGameTime(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameGetReputation(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameSetReputation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_IncreaseReputation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameGetPartyGold(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameSetPartyGold(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameGetFormation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameSetFormation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetJournalSize(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_GetJournalEntry(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_SetJournalEntry(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_GameIsBeastKnown(PyObject * /*self*/, PyObject * args);
PyObject* GemRB_GetINIPartyCount(PyObject * /*self*/, PyObject * /*args*/);
PyObject* GemRB_GetINIQuestsKey(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetINIBeastsKey(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetINIPartyKey(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CreatePlayer(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerStates(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerName(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPlayerName(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CreateString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPlayerString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPlayerSound(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerSound(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSlotType(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPCStats(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameSelectPC(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameIsPCSelected(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameSelectPCSingle(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameGetSelectedPCSingle(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GameGetFirstSelectedPC(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameGetFirstSelectedActor(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GameControlSetLastActor(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ActOnPC(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerPortrait(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerStat(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPlayerStat(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetPlayerScript(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPlayerScript(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPlayerDialog(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_FillPlayerInfo(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetSpellIcon(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetItemIcon(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_EnterStore(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LeaveStore(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_LoadRighthandStore(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CloseRighthandStore(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_LeaveContainer(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GetContainer(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetContainerItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ChangeContainerItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetStore(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_IsValidStoreItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_FindStoreItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetPurchasedAmount(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ChangeStoreItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetStoreItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetStoreDrink(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetStoreCure(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ExecuteString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_EvaluateString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_UpdateMusicVolume(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_UpdateAmbientsVolume(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_MessageWindowDebug(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetCurrentArea(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_MoveToArea(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetMemorizableSpellsCount(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_SetMemorizableSpellsCount(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_CountSpells(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetKnownSpellsCount(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetKnownSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetMemorizedSpellsCount(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetMemorizedSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CheckSpecialSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSpelldataIndex(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSpelldata(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LearnSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_DispelEffect(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_RemoveEffects(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_RemoveSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_RemoveItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_MemorizeSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_UnmemorizeSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSlotItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ChangeItemFlag(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CanUseItemType(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSlots(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_FindItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_DragItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_DropDraggedItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_IsDraggingItem(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_GetSystemVariable(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CreateItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetAvatarsValue(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMapAnimation(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMapnote(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMapDoor(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMapExit(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMapRegion(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CreateCreature(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_RevealArea(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ExploreArea(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetRumour(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GamePause(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CheckFeatCondition(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_HasFeat(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetFeat(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetMaxEncumbrance(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetAbilityBonus(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_LeaveParty(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Button_SetActionIcon(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_HasResource(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetupEquipmentIcons(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_Window_SetupControls(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ClearActions(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetDefaultActions(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetupQuickSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetupQuickSlot(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetEquippedQuickSlot(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetEquippedQuickSlot(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetEquippedAmmunition(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetModalState(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_PrepareSpontaneousCast(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SpellCast(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ApplySpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_UseItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetGamma(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetMouseScrollSpeed(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetTooltipDelay(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetFullScreen(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_RunRestScripts(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_RestParty(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ChargeSpells(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_HasSpecialItem(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_HasSpecialSpell(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ApplyEffect(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_CountEffects(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_ModifyEffect(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_StealFailed(PyObject * /*self*/, PyObject* /*args*/);
PyObject* GemRB_SwapPCs(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_SetRepeatClickFlags(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_DisplayString(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetCombatDetails(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetDamageReduction(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSpellFailure(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_IsDualWielding(PyObject * /*self*/, PyObject* args);
PyObject* GemRB_GetSelectedSize(PyObject* /*self*/, PyObject* /*args*/);
PyObject* GemRB_GetSelectedActors(PyObject* /*self*/, PyObject* /*args*/);
PyObject* GemRB_GetSpellCastOn(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_SetTickHook(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_SetupMaze(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_SetMazeEntry(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_SetMazeData(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_GetMazeHeader(PyObject* /*self*/, PyObject* /*args*/);
PyObject* GemRB_GetMazeEntry(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_AddGameTypeHint(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_GetAreaInfo(PyObject* /*self*/, PyObject* /*args*/);
PyObject* GemRB_Log(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_SetFeature(PyObject* /*self*/, PyObject* args);
PyObject* GemRB_GetMultiClassPenalty(PyObject* /*self*/, PyObject* args);
